filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'
  json.keys_under_root: true
  json.add_error_key: true
  json.ignore_decoding_error: true

processors:
- add_docker_metadata: ~
- add_host_metadata: ~
- decode_json_fields:
    fields: ["message"]
    target: ""
    overwrite_keys: true
    add_error_key: true
- add_fields:
    target: "service"
    fields:
      environment: "dev"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: 'filebeat-%{+yyyy.MM.dd}'
      when.equals:
        app.name: "app-product-api"
    - index: 'filebeat-%{+yyyy.MM.dd}'
      when.equals:
        app.name: "app-product-worker"
    - index: 'filebeat-%{+yyyy.MM.dd}'
      when.equals:
        app.name: "elasticsearch"
    - index: 'filebeat-%{+yyyy.MM.dd}'
      when.equals:
        app.name: "kibana"
    - index: 'filebeat-%{+yyyy.MM.dd}'
      when.equals:
        app.name: "kafka"
    - index: 'filebeat-%{+yyyy.MM.dd}'
      when.equals:
        app.name: "zookeeper"
    - index: 'filebeat-%{+yyyy.MM.dd}'
      when.equals:
        app.name: "mysql"

setup.template.enabled: true
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.ilm.enabled: true
setup.ilm.rollover_alias: "filebeat"
setup.ilm.pattern: "{now/d}-000001"

logging.json: true
logging.metrics.enabled: false
setup.kibana:
  host: "http://kibana:5601"